name: bonline-wazo-calld-update-callerid
namespace: bOnline
version: 0.0.1
author: Christie Grinham
display_name: Update the caller ID of an ongoing call
min_wazo_version: 25.12
tags:
  - experimental
  - application
